### ISSUE TITLE
Collection existence check fails if one collection name is a substring in another 

### ISSUE THREAD

**Issue by bryngemark** [LDMX-Software/Framework#85]
Sometimes when I develop things I name collections with different suffixes to separate them. I have found that if I name them in the style `myCollection` and `myCollectionTwo`, then only the second collection is found when I use `event.exists(inputCol_, inputPassName_)`.

I think this is because 1. the `exists()` method returns `true` only if there is _exactly one_ collection found in by `searchProducts()` and 2. `searchProducts()` seems to be content if it finds a match, and doesn't care if it's a whole string match or substring. 

I suppose this boils down to the behaviour of `regcomp`. Not sure how we want to solve this. Full word match would be my preference. The logic of 1. is probably sound but it could be helpful to spit out a message if there is more than one match. I know this already happens if there are several passes and no pass name was specified. 

To reproduce, just run two instances of a producer of your choice with the above naming scheme, followed by two producers/analyzers using the produced collections. My example is 
1. check out the `TrigScint/lk-testbeamDev` branch
2. run `ldmx fire ${LDMX_BASE}/ldmx-sw/TrigScint/exampleConfigs/runTSsimAndReco.py`
3. and then `ldmx fire ${LDMX_BASE}/ldmx-sw/TrigScint/exampleConfigs/runClusterAna.py [output file] "sim"` after enabling both the 2-hit and 3-hit cluster analysis.

**Comment by tomeichlersmith** [comment]
Thank you for finding and reporting this - I added it to the list for the next minor release since I think we can resolve this either with more documentation of `Event::exists` or patching its underlying implementation.

Generally, my thought for the `Event::exists` method is that it should return `true` whenever `get` would be successful, i.e. users should be able to
```cpp
if (event.exists(...arguments)) {
  const auto& obj = event.getObject<ObjType>(...arguments);
}
```
and the _only_ reason there would be an exception is if `ObjType` is not the correct type for that branch.

_However_, this interpretation of the purpose of `exists` may not align with your understanding of it. Perhaps we change `exists` to be more than `0` collections found and have another function (maybe called `unique`) which requires exactly one collection?

I would like to keep `searchProducts` supportive of whole or sub-string matching and instead focus on defining more helpful methods like `exists`.

> only the second collection is found

Can you be more specific here? If you have `myCollection` and `myCollectionTwo` in the event, I would expect `event.exists("myCollection")` to return `false`, `event.searchProducts("myCollection")` to return a vector of length two, and `event.getObject<MyCollectionType>("myCollection")` to successfully return the values of `myCollection` (as opposed to `myCollectionTwo`). Is this the current behavior?

**Comment by bryngemark** [comment]
So I cross checked, and your expectation is correct. Indeed the values of `myCollection` and `myCollectionTwo` are both properly fetched using `getObject`. The problem is only the inability of `event.exists()` to relay the distinction of the two cases (0 or 2). 

I think I agree with you about the logic -- this is exactly my use case: sometimes there is no collection produced yet in the first event, which means I need to have protections for that case and skip processing the event, lest the whole thing seg faults. And that logic is clearly broken here: I get `exists=false` and the collection is still retrievable. 

I wonder if we can get in trouble for setting `true` in case of one or more collections with substring matches, if somehow someone uses the check for a substring existing in one or two other collections. This would be avoided with a `unique` check. I can see how such a bug would go under the radar.

**Comment by tomeichlersmith** [comment]
> I wonder if we can get in trouble for setting true in case of one or more collections with substring matches, if somehow someone uses the check for a substring existing in one or two other collections. This would be avoided with a unique check. I can see how such a bug would go under the radar.

Can you elaborate more here? I'm unsure on what the bug is in this case. Do you mean some code is relying on the unique-ness aspect of `exists` as currently implemented?

---

Just some more notes for us about the current implementation and some possible improvements.

The current `exists` just passes the parameters along to `searchProducts` and makes sure the list of returns is length one.

https://github.com/LDMX-Software/Framework/blob/f3e75bccfe789213ac53c1f8d2c5b50ab76f9cc3/include/Framework/Event.h#L105-L107

`searchProducts` does not do anything with the input except evolve empty strings into the match-all pattern `.*`.

https://github.com/LDMX-Software/Framework/blob/f3e75bccfe789213ac53c1f8d2c5b50ab76f9cc3/src/Framework/Event.cxx#L38-L44

So, I'm imagining a few more `exists`-like functions that can match this various use case.

```cpp
// change exists to mean exists, (i.e. one or more)
bool exists(const std::string& name, const std::string& passname = "") const {
  return searchProducts(name, passname, "").size() > 0;
}

// check for unique-ness (i.e. the current exists)
bool unique(const std::string& name, const std::string& passname = "") const {
  return searchProducts(name, passname, "").size() == 1;
}

// no substring matching, basically we use begin-of-line ^ and end-of-line $ regex symbols to force full-string match
bool exists_strict(const std::string& name, const std::string& passname = "") const {
  std::string name_regex{name}, pass_regex{passname};
  if (not name_regex.empty()) name_regex = "^"+name_regex+"$";
  if (not pass_regex.empty()) pass_regex = "^"+pass_regex+"$";
  return exists(name_regex, pass_regex);
}

// and the same for unique
```

**Comment by bryngemark** [comment]
I meant if someone uses `exists` to verify that `myCollection` exists, and then does something, but in reality only `myCollectionOne` and `myCollectionTwo` exist. Let's say someone adds collections with several instances of some producer (like I did) so the pass name is identical, and then by mistake forgets to use `One` or `Two` in the input name for the consuming processor. Then they would be like "but the collection exists, why is my code crashing???"
-- ok this might be a very contrived scenario 😄

**Comment by tomeichlersmith** [comment]
No that's a good point - I'm now thinking of a new contributor who just wants to write something that analyzes the simulation. They've heard of this thing called sim hits and so they end up using
```
event.exists("SimHits")
```
after poking around the docs and what not which will return `true` but `get` will fail because there are many different kinds of SimHits.

I think the way out of this issue is to add more detail to the `exists` documentation and point folks to the `searchProducts` function so that while they are poking around they get the full picture. Using `searchProducts` directly like
```cpp
auto matches{event.searchProducts(...args...)};
std::cout << "Found " << matches.size() << " matches" << std::endl;
for (const auto& match : matches) {
  std::cout << match << std::endl;
}
```
will give a more full picture of the situation and allows users to do more complicated things (perhaps they want to include _all_ collections of a given match?)
